"""mudanças no rastreio

Revision ID: 007b825209d4
Revises: d845de1da52d
Create Date: 2022-07-12 04:36:10.046446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007b825209d4'
down_revision = 'd845de1da52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rastreio', 'verificado')
    op.drop_column('rastreio', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rastreio', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rastreio', sa.Column('verificado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
