"""revisão no rastreio

Revision ID: 017df81dd99f
Revises: c27ce5fd6ade
Create Date: 2022-07-12 06:34:36.922469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017df81dd99f'
down_revision = 'c27ce5fd6ade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_encomenda_id'), 'encomenda', ['id'], unique=False)
    op.create_index(op.f('ix_exemplo_id'), 'exemplo', ['id'], unique=False)
    op.add_column('rastreio', sa.Column('lido', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rastreio', 'lido')
    op.drop_index(op.f('ix_exemplo_id'), table_name='exemplo')
    op.drop_index(op.f('ix_encomenda_id'), table_name='encomenda')
    # ### end Alembic commands ###
