"""mudanças no rastreio

Revision ID: 20d0990924ce
Revises: 007b825209d4
Create Date: 2022-07-12 04:39:09.181303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d0990924ce'
down_revision = '007b825209d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
