"""mudanças no rastreio

Revision ID: 27cdd44188a3
Revises: a63fe09efbfe
Create Date: 2022-07-12 06:12:39.703093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cdd44188a3'
down_revision = 'a63fe09efbfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
