"""mudanças na encomenda

Revision ID: 31226004de63
Revises: e8daa41ad77d
Create Date: 2022-07-12 05:59:03.651369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31226004de63'
down_revision = 'e8daa41ad77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
