"""Add novos bancos

Revision ID: 3f04f3d4f6d6
Revises: 58b7a95d4e2c
Create Date: 2022-07-08 04:32:14.606965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f04f3d4f6d6'
down_revision = '58b7a95d4e2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rastreio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('atualizacao', sa.Date(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('mudanca', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rastreio_codigo'), 'rastreio', ['codigo'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_telegram', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_id_telegram'), 'usuario', ['id_telegram'], unique=False)
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('rastreio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rastreio_id'], ['rastreio.id'], name='fk_encomenda_rastreio'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_encomenda_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomenda')
    op.drop_index(op.f('ix_usuario_id_telegram'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rastreio_codigo'), table_name='rastreio')
    op.drop_table('rastreio')
    # ### end Alembic commands ###
