"""mudanças no rastreio

Revision ID: 582c8725c95b
Revises: 9001cd85b3a9
Create Date: 2022-07-12 06:03:42.193850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c8725c95b'
down_revision = '9001cd85b3a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
