"""mudanças no rastreio

Revision ID: 7337486288d9
Revises: 582c8725c95b
Create Date: 2022-07-12 06:08:02.462533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7337486288d9'
down_revision = '582c8725c95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
