"""mudanças no rastreio

Revision ID: 7aaea1aa8c3a
Revises: 27cdd44188a3
Create Date: 2022-07-12 06:12:44.217708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaea1aa8c3a'
down_revision = '27cdd44188a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
