"""mudanças na encomenda e rastreio

Revision ID: 9001cd85b3a9
Revises: 31226004de63
Create Date: 2022-07-12 06:02:22.818205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9001cd85b3a9'
down_revision = '31226004de63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
