"""mudanças no rastreio

Revision ID: a63fe09efbfe
Revises: 7337486288d9
Create Date: 2022-07-12 06:11:41.657860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63fe09efbfe'
down_revision = '7337486288d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
