"""revisão geral

Revision ID: c27ce5fd6ade
Revises: 7aaea1aa8c3a
Create Date: 2022-07-12 06:20:23.212046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27ce5fd6ade'
down_revision = '7aaea1aa8c3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
