"""novas adições no usuário

Revision ID: d845de1da52d
Revises: 562a407e14ef
Create Date: 2022-07-12 04:07:05.016366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd845de1da52d'
down_revision = '562a407e14ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
