"""mudanças na encomenda

Revision ID: e8daa41ad77d
Revises: 20d0990924ce
Create Date: 2022-07-12 05:18:42.228585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8daa41ad77d'
down_revision = '20d0990924ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
